name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Log in to Docker Hub
      uses: actions/docker/login@master
      secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    - name: Build Docker image
      run: docker build --tag junitteam/build:latest --tag junitteam/build:$(date +%s) .
    - name: Push Docker image
      run: docker push junitteam/build
