name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: JDK 11 (Default)
      uses: elgohr/Publish-Docker-Github-Action@e0635c0
      with:
        name: junitteam/build
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: JDK 12
      uses: elgohr/Publish-Docker-Github-Action@e0635c0
      env:
        ADDITIONAL_JDK_VERSION: 12.0.2-open
      with:
        name: junitteam/build:12
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: ADDITIONAL_JDK_VERSION
    - name: JDK 13
      uses: elgohr/Publish-Docker-Github-Action@e0635c0
      env:
        ADDITIONAL_JDK_VERSION: 13.0.1-open
      with:
        name: junitteam/build:13
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: ADDITIONAL_JDK_VERSION
    - name: JDK 14
      uses: elgohr/Publish-Docker-Github-Action@e0635c0
      env:
        ADDITIONAL_JDK_VERSION: 14.ea.18-open
      with:
        name: junitteam/build:14
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: ADDITIONAL_JDK_VERSION
